[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = ".next"
  exclude = [
    '**/components',
    '**/components/**',

    '.next/pages/datenschutz',
    './.next/pages/datenschutz',
    '.next/datenschutz',

    '/impressum',
    '/pages/impressum',
    
  ]