[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  exclude = [
    # By file Path
    './build-dir/path-to/file.html',
    # By Glob pattern
    '**/**/child-one.html',
    '**/components',
    '**/components/**',
    '**/funnel',
    '**/funnel/**',
    './public/pages/datenschutz.js',
    './public/pages/impressum.js',
    './public/pages/scalarone.js',
    './public/pages/thank-you.js',
    
  ]